### Get a list of movies

GET http://localhost:3000/movies

### Get a particular movie

GET http://localhost:3000/movies/8

### Create a movie

POST http://localhost:3000/movies
content-type: application/json

{
    "title": "Forest Gump",
    "description": "Great film",
    "moods": [
        "Inspiring",
        "Kind"
    ]
}

### Update a movie

PATCH http://localhost:3000/movies/8
content-type: application/json

{
    "description": "Great film ever"
}

### Delete a movie

DELETE http://localhost:3000/movies/8

### Login a user


POST http://localhost:3000/auth/login
content-type: application/json

{
    "username": "john", 
    "password": "changeme"
} 


### Get user profile

POST http://localhost:3000/profile 
authorization: Bearer 
